services:
  rdancer-utility-worker:
    image: rdancer/rdancer-utility-worker:0.0.0-rc1
    build:
      context: .
    volumes:
      - ./workspace:/workspace
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
