version: '3.7'

services:
  rdancer-comfyui-worker:
    image: rdancer/runpod-worker-comfyui:0.0.30
    build:
      context: .
      args:
        MY_BASE_IMAGE: timpietruskyblibla/runpod-worker-comfy:3.1.2-base
        IMAGE_TYPE: comfyui
    container_name: rdancer-comfyui-worker
    environment:
      - COMFYUI_API_URL=https://comfyui-api.example.com
      - COMFYUI_API_TOKEN=your-api-token
      - COMFYUI_API_SECRET=your-api-secret
    restart: always

  rdancer-deforum-worker:
    image: rdancer/runpod-worker-deforum:0.0.30
    build:
      context: .
      args:
        MY_BASE_IMAGE: ghcr.io/ai-dock/stable-diffusion-webui:v2-cuda-12.1.1-base-22.04-v1.10.1
        IMAGE_TYPE: deforum
    container_name: rdancer-deforum-worker
    environment:
      - WEBUI_ARGS=--xformers --no-half-vae --api --deforum-api # This is required
      - WEBUI_VENV=/workspace/environments/python/webui
      - WORKSPACE=/workspace
    ports:
      - "17860:17860"  # Web UI port
      - "5678:5678"  # Debugger port
    restart: always
